import React,{useEffect,useRef,useState} from 'react'
export default function CameraCapture({onPhoto}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('')
 const video=useRef(null),stream=useRef(null),serial=useRef(0),fallback=useRef(null)
 function stop(){serial.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null}
 function close(){stop();setOpen(false);setBusy(false);setReady(false)}
 useEffect(()=>{const hide=()=>{if(document.hidden)close()};document.addEventListener('visibilitychange',hide);return()=>{stop();document.removeEventListener('visibilitychange',hide)}},[])
 useEffect(()=>{if(open&&stream.current&&video.current){video.current.srcObject=stream.current;video.current.play().catch(()=>{})}},[open])
 async function start(){if(busy)return;setError('');if(!navigator.mediaDevices?.getUserMedia){fallback.current?.click();return}stop();const id=serial.current;setBusy(true);setReady(false);try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:1280}},audio:false});if(id!==serial.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;setOpen(true)}catch(e){if(id===serial.current)setError(e.name==='NotAllowedError'?'กรุณาอนุญาตใช้กล้องในเบราว์เซอร์ หรือเลือกไฟล์รูปแทน':e.name==='NotFoundError'?'ไม่พบกล้องในอุปกรณ์นี้ กรุณาเลือกไฟล์รูปแทน':'เปิดกล้องไม่ได้ กรุณาปิดแอปที่ใช้กล้องแล้วลองใหม่')}finally{if(id===serial.current)setBusy(false)}}
 function capture(){const v=video.current;if(!v?.videoWidth||!v.videoHeight)return;const c=document.createElement('canvas'),ratio=Math.min(1,1600/Math.max(v.videoWidth,v.videoHeight));c.width=Math.round(v.videoWidth*ratio);c.height=Math.round(v.videoHeight*ratio);c.getContext('2d').drawImage(v,0,0,c.width,c.height);close();const id=serial.current;c.toBlob(blob=>{if(blob&&id===serial.current)onPhoto(new File([blob],'camera.jpg',{type:'image/jpeg'}))},'image/jpeg',0.9)}
 return <div><input ref={fallback} type="file" accept="image/*" capture="user" hidden onChange={e=>{const f=e.target.files?.[0];if(f)onPhoto(f);e.target.value=''}}/>{!open&&<button type="button" className="btn secondary" disabled={busy} onClick={start}>{busy?'กำลังเปิดกล้อง…':'เปิดกล้องถ่ายรูป'}</button>}{busy&&<button type="button" className="btn secondary" onClick={close}>ยกเลิก</button>}{open&&<div><video ref={video} autoPlay muted playsInline onLoadedData={()=>setReady(true)} style={{display:'block',width:'100%',maxHeight:320,objectFit:'contain',background:'#111',borderRadius:12}}/><div className="actions"><button type="button" className="btn primary" disabled={!ready} onClick={capture}>ถ่ายรูป</button><button type="button" className="btn secondary" onClick={close}>ปิดกล้อง</button></div></div>}{error&&<p role="alert">{error}</p>}</div>
}
