import React,{useEffect,useRef,useState} from 'react'
import {supabase} from './supabase'
import {deriveKinship} from './kinship'
import {displayName,matchesName,nameDefaults} from './personNames'
import {titleGroups} from './nameTitle'
import HouseMap from './HouseMap'
import PeoplePicker from './PeoplePicker'
import LegacyApp from './LegacyApp'
const fields=[['first_name','ชื่อปัจจุบัน'],['last_name','นามสกุลปัจจุบัน'],['birth_first_name','ชื่อเดิมแต่เกิด'],['birth_last_name','นามสกุลเดิมแต่เกิด'],['nickname','ชื่อเล่น'],['birth_date','วันเกิด (ค.ศ.)','date'],['death_date','วันที่เสียชีวิต (ค.ศ.)','date'],['birthplace','บ้านเกิด'],['phone','เบอร์ติดต่อ','tel'],['current_address','ที่อยู่ปัจจุบัน'],['biography','ประวัติและเรื่องราว']]
const homeFields=[['name','ชื่อเรียกบ้านครอบครัว'],['address_line','บ้านเลขที่ หมู่ ถนน'],['subdistrict','ตำบล / แขวง'],['district','อำเภอ / เขต'],['province','จังหวัด'],['postal_code','รหัสไปรษณีย์'],['phone','เบอร์ติดต่อบ้าน']]
const roles={father:'บิดา',mother:'มารดา',spouse:'คู่สมรส',child:'ลูก',older_sibling:'พี่'}
export function linkPermitted(d,a,b,t){return !!a&&!!b&&a.id!==b.id&&(d.is_admin||(t!=='older_sibling'&&((a.home_id===b.home_id&&a.home_id===d.account?.home_id)||(a.id===d.account?.person_id&&['father','mother','spouse'].includes(t)))))}
export default function Dashboard({user}){
 const [d,setD]=useState({homes:[],people:[],relations:[],requests:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[legacy,setLegacy]=useState(false)
 const [home,setHome]=useState(''),[selected,setSelected]=useState(''),[q,setQ]=useState(''),[modal,setModal]=useState(null),lock=useRef(false)
 async function load(){const {data,error}=await supabase.rpc('family_dashboard');if(error){if(error.code==='PGRST202'){setLegacy(true);return}throw error}setLegacy(false);setD(data);setSelected(s=>data.people.some(p=>p.id===s)?s:data.account?.person_id||'')}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 async function act(action,payload){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{const {error}=await supabase.rpc('family_action',{action,payload});if(error)throw error;setModal(null);setNotice('บันทึกแล้ว');try{await load()}catch(e){setError('บันทึกแล้ว แต่โหลดข้อมูลล่าสุดไม่สำเร็จ: '+e.message)}}catch(e){setError(e.code==='23505'?'มีข้อมูลหรือคำขอนี้แล้ว กรุณาตรวจสอบ':e.message)}finally{lock.current=false;setBusy(false)}}
 const p=d.people.find(x=>x.id===selected),h=d.homes.find(x=>x.id===home),myHome=d.homes.find(x=>x.id===d.account?.home_id)
 const name=id=>displayName(d.people.find(x=>x.id===id)),homeName=id=>d.homes.find(x=>x.id===id)?.name||'ยังไม่ระบุบ้าน'
 function choose(x){if(x){setSelected(x.id);setHome(x.home_id||'')}}
 function chooseHome(id){setHome(id);setSelected(d.people.find(x=>x.home_id===id)?.id||'')}
 function open(m){setError('');setModal(m)}
 const kin=deriveKinship(selected,d.people,d.relations),connected=d.relations.filter(r=>r.person_id===selected||r.related_person_id===selected)
 const groups=[['บิดา','father',connected.filter(r=>r.related_person_id===selected&&r.relationship_type==='father').map(r=>[r.person_id,'พ่อ'])],['มารดา','mother',connected.filter(r=>r.related_person_id===selected&&r.relationship_type==='mother').map(r=>[r.person_id,'แม่'])],['คู่สมรส','spouse',connected.filter(r=>r.relationship_type==='spouse').map(r=>[r.person_id===selected?r.related_person_id:r.person_id,'คู่สมรส'])],['ลูก','child',connected.filter(r=>r.person_id===selected&&['father','mother'].includes(r.relationship_type)).map(r=>[r.related_person_id,'ลูก'])],['พี่และน้อง',null,kin.siblings],['ลูกพี่ลูกน้อง',null,kin.cousins]]
 if(legacy)return <><p className="alert">ต้องรัน SQL บ้านครอบครัวก่อนเปิด Dashboard กลาง ข้อมูลเดิมยังใช้งานได้ด้านล่าง</p><LegacyApp/></>
 return <div className="shell"><header className="topbar"><a className="brand" href="#top"><b>ส</b><span><strong>สายใยครอบครัว</strong><small>สาริบุตร</small></span></a><span className="account-email">{user.email}{d.is_admin?' · Admin':''}</span><button className="btn secondary" disabled={busy} onClick={async()=>{const {error}=await supabase.auth.signOut();if(error)setError(error.message)}}>ออกจากระบบ</button></header>
 <main className="workspace" id="top"><div className="heading"><div><p className="eyebrow">บ้านและเครือญาติของเรา</p><h1>Dashboard ครอบครัว</h1><p>{d.homes.length} บ้าน · {d.people.length} คน</p></div><div className="actions"><button className="btn secondary" onClick={()=>open({type:'join'})}>บ้านและตัวฉัน</button>{(!d.account||d.is_admin)&&<button className="btn primary" onClick={()=>open({type:'home'})}>+ สร้างบ้าน</button>}</div></div>
 {error&&<p className="alert" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}{loading?<p>กำลังโหลด…</p>:<>
 <div className="map-panel"><HouseMap homes={d.homes} selected={home} onSelect={chooseHome}/><p className="map-caption">พิกัดบนแผนที่กลางเป็นตำแหน่งโดยประมาณ · คลิกหมุดหรือเลือกบ้านด้านล่างเพื่อดูสมาชิก</p></div>
 <div className="toolbar"><input aria-label="ค้นหาชื่อหรือบ้าน" placeholder="ค้นหาชื่อ ชื่อเดิม นามสกุล ชื่อเล่น หรือบ้าน" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn secondary" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>โหลดใหม่</button></div>
 <div className="home-tabs"><button className={'chip '+(!home?'active':'')} onClick={()=>setHome('')}>ทุกบ้าน</button>{d.homes.filter(x=>!q||x.name.includes(q)||d.people.some(y=>y.home_id===x.id&&matchesName(y,q))).map(x=><button className={'chip '+(home===x.id?'active':'')} key={x.id} onClick={()=>chooseHome(x.id)}>{x.name} · {x.member_count} คน{x.id===myHome?.id?' · บ้านฉัน':''}</button>)}</div>
 {h&&<section className="house-info"><div className="heading"><div><h2>{h.name}</h2><p>{[h.district,h.province].filter(Boolean).join(' · ')||'ยังไม่ระบุพื้นที่'}</p></div>{h.can_edit&&<button className="btn secondary" onClick={()=>open({type:'home',house:h})}>แก้ไขบ้าน</button>}</div>{h.can_edit?<p>{[h.address_line,h.subdistrict,h.district,h.province,h.postal_code].filter(Boolean).join(' ')}<br/>เบอร์: {h.phone||'ยังไม่ระบุ'} · ผู้ประสานงาน: {h.coordinator_id?name(h.coordinator_id):'ยังไม่ระบุ'}</p>:<p>ข้อมูลติดต่อและที่อยู่ละเอียดสงวนให้สมาชิกบ้านและ Admin</p>}</section>}
 <div className="family-grid"><section className="members-panel"><div className="heading"><h2>สมาชิก</h2>{(myHome||d.is_admin)&&<button className="btn secondary" onClick={()=>open({type:'person',homeId:h?.can_edit?h.id:myHome?.id})}>+ เพิ่ม</button>}</div>{d.people.filter(x=>(!home||x.home_id===home)&&(!q||matchesName(x,q)||homeName(x.home_id).includes(q))).map(x=><button className={'member-card '+(selected===x.id?'selected':'')} key={x.id} onClick={()=>choose(x)}><span className="avatar green">{(x.first_name||x.full_name).slice(0,1)}</span><span><strong>{displayName(x)}</strong><small>{homeName(x.home_id)}{x.nickname?' · '+x.nickname:''}</small></span></button>)}{!d.people.length&&<p>เริ่มสร้างบ้านและเพิ่มสมาชิก หรือขอเข้าร่วมบ้านที่มีอยู่</p>}</section>
 {p?<section className="person-panel"><div className="heading"><div><h2>{displayName(p)}</h2><p>{homeName(p.home_id)} · {p.can_edit?'แก้ไขได้':'อ่านอย่างเดียว'}</p></div>{p.can_edit&&<button className="btn secondary" onClick={()=>open({type:'person',person:p,homeId:p.home_id})}>แก้ไข</button>}</div>
 <dl className="facts">{[['เพศ',p.kinship_gender==='male'?'ชาย':p.kinship_gender==='female'?'หญิง':null],...fields.filter(([k])=>p.can_edit||['first_name','last_name','birth_first_name','birth_last_name','nickname'].includes(k)).map(([k,l])=>[l,['birth_first_name','birth_last_name'].includes(k)?(p[k]?.trim()||'เหมือนปัจจุบัน'):p[k]])].map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v||'ยังไม่ระบุ'}</dd></div>)}</dl>{!p.can_edit&&<p className="privacy-note">วันเกิด เบอร์โทร ประวัติ และที่อยู่ปัจจุบันเป็นข้อมูลสงวน</p>}
 <div className="heading"><h2>เครือญาติของบุคคลนี้</h2>{d.is_admin&&<button className="btn secondary" onClick={()=>open({type:'link',anchor:p,role:'older_sibling'})}>Admin: เชื่อมพี่น้อง</button>}</div><p className="map-caption">พี่น้องและลูกพี่ลูกน้องคำนวณจากความสัมพันธ์ที่เชื่อมไว้ หากไม่มีวันเกิดที่เข้าถึงได้ จะไม่เดาลำดับอายุ</p>
 <div className="relation-groups">{groups.map(([label,role,items])=><section key={label}><h3>{label}</h3>{items.map(([id,r])=><button className="relative" key={id+r} onClick={()=>choose(d.people.find(x=>x.id===id))}>{name(id)}<small>({r})</small></button>)}{!items.length&&<p>ยังไม่ได้เชื่อมข้อมูล</p>}{role&&(p.can_edit||p.id===d.account?.person_id)&&(!['father','mother'].includes(role)||!items.length)&&<button className="btn secondary small" onClick={()=>open({type:'link',anchor:p,role})}>เลือกชื่อ / + เพิ่ม{label}</button>}</section>)}</div>
 <details><summary>จัดการความสัมพันธ์</summary>{connected.map(r=><div className="relation-line" key={r.id}><span>{name(r.person_id)} — {roles[r.relationship_type]}ของ — {name(r.related_person_id)}</span>{r.can_edit&&<button className="btn secondary" disabled={busy} onClick={()=>{if(confirm('ยกเลิกความสัมพันธ์นี้?'))act('unlink',{id:r.id})}}>ยกเลิก</button>}</div>)}</details>{d.is_admin&&<button className="btn danger" disabled={busy} onClick={()=>{if(confirm('ลบบุคคลนี้และความสัมพันธ์ทั้งหมด?'))act('delete_person',{id:p.id})}}>ลบบุคคลนี้</button>}</section>:<section className="person-panel"><h2>เลือกบ้านหรือสมาชิก</h2><p>คลิกหมุดหรือรายชื่อเพื่อดูข้อมูลและเครือญาติ</p></section>}</div>
 {d.is_admin&&<section className="house-info"><h2>Admin · คำขอเข้าบ้านและยืนยันตัวบุคคล</h2>{d.requests.filter(r=>r.status==='pending').map(r=><div className="request-row" key={r.id}><div><strong>{r.email}</strong><p>{homeName(r.home_id)} · {r.person_id?name(r.person_id):'ยังไม่ผูกบุคคล'}</p><p>{r.note}</p></div><div className="actions"><button className="btn primary" disabled={busy} onClick={()=>{if(confirm('ตรวจสอบแล้วว่าบัญชีนี้เป็นสมาชิกบ้านและบุคคลนี้จริง?'))act('review_request',{id:r.id,decision:'approved'})}}>อนุมัติ</button><button className="btn secondary" disabled={busy} onClick={()=>act('review_request',{id:r.id,decision:'rejected'})}>ไม่อนุมัติ</button></div></div>)}{!d.requests.some(r=>r.status==='pending')&&<p>ไม่มีคำขอรอตรวจสอบ</p>}</section>}
 </> }</main>
 {modal&&<div className="backdrop"><section className="modal wide-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><h2 id="modal-title">{{home:'บ้านครอบครัว',person:modal.person?'แก้ไขข้อมูล':'เพิ่มบุคคล',link:'เชื่อม'+roles[modal.role],join:'บ้านและตัวฉัน'}[modal.type]}</h2><button aria-label="ปิด" disabled={busy} onClick={()=>setModal(null)}>×</button></header>{error&&<p className="alert" role="alert">{error}</p>}
 {modal.type==='home'&&<HomeForm house={modal.house} people={d.people} busy={busy} onSave={v=>act('save_home',v)}/>}
 {modal.type==='person'&&<PersonForm person={modal.person} homeId={modal.homeId} data={d} busy={busy} link={modal.link} onSelect={x=>{if(modal.link)open({type:'link',...modal.link,chosen:x});else{choose(x);setModal(null)}}} onSave={v=>act('save_person',v)}/>}
 {modal.type==='link'&&<LinkForm data={d} anchor={modal.anchor} role={modal.role} chosen={modal.chosen} busy={busy} onSave={v=>act('link',v)} onNew={parentRole=>open({type:'person',homeId:modal.anchor.home_id,link:{anchor:modal.anchor,role:modal.role,parentRole}})}/>}
 {modal.type==='join'&&<JoinForm data={{...d,requests:d.requests.filter(r=>r.user_id===user.id)}} busy={busy} onSave={v=>act('request_join',v)}/>}
 </section></div>}
 </div>
}
function PersonForm({person,homeId,data,busy,link,onSave,onSelect}){
 const defaults=nameDefaults(person),[first,setFirst]=useState(defaults.first_name),[last,setLast]=useState(defaults.last_name),[distinct,setDistinct]=useState(false),[targetHome,setTargetHome]=useState(homeId||data.account?.home_id||'')
 const search=[first,last].filter(Boolean).join(' '),matches=!person&&search.trim()?data.people.filter(p=>matchesName(p,search)):[]
 return <form className="form" onSubmit={e=>{e.preventDefault();onSave({...Object.fromEntries(new FormData(e.currentTarget)),id:person?.id,home_id:targetHome,confirm_distinct:distinct,...(link?{link_anchor:link.anchor.id,link_role:link.role,parent_role:link.parentRole}:{})})}}>
 {link&&<p>เพิ่ม{roles[link.role]}ของ {displayName(link.anchor)} · บันทึกและเชื่อมพร้อมกัน</p>}
 <label>บ้านครอบครัว<select required disabled={!data.is_admin} value={targetHome} onChange={e=>setTargetHome(e.target.value)}><option value="">เลือกบ้าน</option>{data.homes.filter(h=>h.can_edit).map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label>
 <label>คำนำหน้านาม<select name="name_title" defaultValue={defaults.name_title}><option value="">ไม่ระบุ / คำนำหน้าอื่น</option>{titleGroups.map(([g,ts])=><optgroup key={g} label={g}>{ts.map(t=><option key={t} value={t}>{t}</option>)}</optgroup>)}</select></label>
 <label>เพศ<select name="kinship_gender" required defaultValue={person?.kinship_gender||''}><option value="" disabled>เลือกเพศ</option><option value="male">ชาย</option><option value="female">หญิง</option></select></label>
 {person&&person.first_name==null&&<p>ข้อมูลเดิมเก็บชื่อรวมไว้ กรุณาตรวจสอบและแยกชื่อกับนามสกุล</p>}
 <label>ชื่อปัจจุบัน<input name="first_name" required maxLength={200} value={first} onChange={e=>{setFirst(e.target.value);setDistinct(false)}} autoComplete="off"/></label><label>นามสกุลปัจจุบัน<input name="last_name" maxLength={200} value={last} onChange={e=>{setLast(e.target.value);setDistinct(false)}} autoComplete="off"/></label>
 {matches.length>0&&<div className="pick-results"><p>พบชื่อใกล้เคียง เลือกบุคคลเดิมได้เลย</p>{matches.slice(0,15).map(p=><button type="button" key={p.id} onClick={()=>onSelect(p)}><strong>{displayName(p)}</strong><small>{data.homes.find(h=>h.id===p.home_id)?.name}</small></button>)}</div>}
 {!person&&<label className="check-label"><input type="checkbox" checked={distinct} onChange={e=>setDistinct(e.target.checked)}/>ตรวจสอบแล้ว ยืนยันว่าเป็นบุคคลใหม่คนละคน</label>}
 {fields.slice(2).map(([k,l,t])=><label key={k}>{l}{['biography','current_address'].includes(k)?<textarea name={k} defaultValue={person?.[k]||''} rows={3}/>:<input name={k} type={t||'text'} defaultValue={person?.[k]||''} maxLength={200} placeholder={k==='birth_first_name'?'กรอกเมื่อชื่อปัจจุบันไม่ตรงชื่อแต่เกิด':k==='birth_last_name'?'กรอกเมื่อนามสกุลปัจจุบันไม่ตรงนามสกุลแต่เกิด':undefined}/>}</label>)}<button className="btn primary" disabled={busy||(!person&&matches.length>0&&!distinct)}>{busy?'กำลังบันทึก…':'บันทึกข้อมูล'}</button></form>
}
function LinkForm({data,anchor,role,chosen,busy,onSave,onNew}){
 const [target,setTarget]=useState(chosen||null),[parentRole,setParentRole]=useState(anchor.kinship_gender==='female'?'mother':'father'),allowed=target&&linkPermitted(data,anchor,target,role)
 return <div className="form"><p>เลือก{roles[role]}ของ <strong>{displayName(anchor)}</strong></p><PeoplePicker people={data.people} homes={data.homes} exclude={[anchor.id]} onSelect={setTarget}/>{role==='child'&&<label>บุคคลหน้านี้เป็น<select value={parentRole} onChange={e=>setParentRole(e.target.value)}><option value="father">พ่อของลูก</option><option value="mother">แม่ของลูก</option></select></label>}{target&&<><p className={allowed?'success':'alert'}>{displayName(target)}{allowed?'':' — ไม่มีสิทธิ์เชื่อมคู่นี้ กรุณาติดต่อ Admin'}</p><button className="btn primary" disabled={busy||!allowed} onClick={()=>{const reverse=['father','mother','older_sibling'].includes(role);onSave({person_id:reverse?target.id:anchor.id,related_person_id:reverse?anchor.id:target.id,relationship_type:role==='child'?parentRole:role})}}>ใช้บุคคลนี้และเชื่อมความสัมพันธ์</button></>}{role!=='older_sibling'&&(data.is_admin||anchor.home_id===data.account?.home_id)&&<button className="btn secondary" disabled={busy} onClick={()=>onNew(parentRole)}>ไม่พบในระบบ · + เพิ่ม{roles[role]}</button>}<p>ข้ามบ้านได้เฉพาะบิดา มารดา และคู่สมรสของตัวฉันที่ยืนยันแล้ว ลูกข้ามบ้านให้ Admin เชื่อม</p></div>
}
function HomeForm({house,people,busy,onSave}){
 const [point,setPoint]=useState([house?.exact_latitude??'',house?.exact_longitude??''])
 return <form className="form" onSubmit={e=>{e.preventDefault();onSave({...Object.fromEntries(new FormData(e.currentTarget)),id:house?.id,exact_latitude:point[0],exact_longitude:point[1]})}}>{homeFields.map(([k,l])=><label key={k}>{l}<input name={k} required={k==='name'} maxLength={200} defaultValue={house?.[k]||''}/></label>)}<label>ผู้ประสานงานบ้าน<select name="coordinator_id" defaultValue={house?.coordinator_id||''}><option value="">ยังไม่ระบุ</option>{people.filter(p=>p.home_id===house?.id).map(p=><option key={p.id} value={p.id}>{displayName(p)}</option>)}</select></label><p>คลิกแผนที่ปักหมุด หรือกรอกพิกัดบ้านจริง พิกัดละเอียดสงวนให้สมาชิกบ้านและ Admin</p><HouseMap point={point} onPoint={setPoint}/><div className="coordinate-fields">{['ละติจูด','ลองจิจูด'].map((l,i)=><label key={l}>{l}<input type="number" step="any" min={i?-180:-90} max={i?180:90} value={point[i]} onChange={e=>setPoint(p=>p.map((v,j)=>j===i?e.target.value:v))}/></label>)}</div><button type="button" className="btn secondary" onClick={()=>setPoint(['',''])}>ล้างพิกัด</button><button className="btn primary" disabled={busy}>บันทึกบ้าน</button></form>
}
function JoinForm({data,busy,onSave}){
 const [home,setHome]=useState(data.account?.home_id||''),[person,setPerson]=useState(null)
 return <form className="form" onSubmit={e=>{e.preventDefault();onSave({home_id:home,person_id:person?.id,note:new FormData(e.currentTarget).get('note')})}}><p>บ้านปัจจุบัน: {data.homes.find(h=>h.id===data.account?.home_id)?.name||'ยังไม่ได้เข้าบ้าน'}<br/>ตัวฉัน: {data.account?.person_id?displayName(data.people.find(p=>p.id===data.account.person_id)):'ยังไม่ได้ยืนยัน'}</p><label>บ้านที่ขอเข้าร่วม<select required value={home} onChange={e=>{setHome(e.target.value);setPerson(null)}}><option value="">เลือกบ้าน</option>{data.homes.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label>{home&&<PeoplePicker key={home} label="ค้นหาชื่อของตัวฉันในบ้านนี้" people={data.people.filter(p=>p.home_id===home)} homes={data.homes} onSelect={setPerson}/>}{person&&<p className="success">ตัวฉันคือ {displayName(person)} <button type="button" onClick={()=>setPerson(null)}>ล้าง</button></p>}<label>ข้อความถึง Admin<textarea name="note" maxLength={1000} placeholder="ข้อมูลสำหรับตรวจสอบว่าเป็นสมาชิกบ้านและบุคคลนี้จริง"/></label><p>สิทธิ์จะเปลี่ยนเมื่อ Admin ตรวจสอบและอนุมัติ</p><button className="btn primary" disabled={busy||data.requests.some(r=>r.status==='pending')}>ส่งคำขอให้ Admin</button>{data.requests.map(r=><p key={r.id}>คำขอ: {{pending:'รออนุมัติ',approved:'อนุมัติแล้ว',rejected:'ไม่อนุมัติ'}[r.status]}</p>)}</form>
}
