import CameraCapture from './CameraCapture'
import React,{useEffect,useRef,useState} from 'react'
export default function PhotoCrop({person}){
 const [source,setSource]=useState(null),[zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[photo,setPhoto]=useState(null),[error,setError]=useState('')
 const canvas=useRef(null),generation=useRef(0)
 useEffect(()=>()=>{generation.current++},[])
 useEffect(()=>{if(!source||!canvas.current)return;const c=canvas.current,ctx=c.getContext('2d'),size=Math.min(source.width,source.height)/zoom;ctx.fillStyle='#fff';ctx.fillRect(0,0,256,256);ctx.drawImage(source,(source.width-size)*x/100,(source.height-size)*y/100,size,size,0,0,256,256)},[source,zoom,x,y])
 async function select(file){const id=++generation.current;setError('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('เลือกรูป JPG, PNG หรือ WebP ขนาดไม่เกิน 10 MB');return}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);if(id!==generation.current)return;setSource(img);setZoom(1);setX(50);setY(50)};img.onerror=()=>{URL.revokeObjectURL(url);if(id===generation.current)setError('เปิดรูปไม่ได้ กรุณาเลือกใหม่')};img.src=url}
 return <fieldset className="form"><legend>รูปโปรไฟล์</legend>{photo!==null&&<input type="hidden" name="avatar_image" value={photo}/>}{(photo||person?.avatar_url)&&<img src={photo||person.avatar_url} alt="รูปโปรไฟล์" style={{width:90,height:90,borderRadius:'50%',objectFit:'cover'}}/>}<label>เลือกรูป<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>select(e.target.files?.[0])}/></label><CameraCapture onPhoto={select}/>{source&&<><canvas ref={canvas} width="256" height="256" aria-label="ตัวอย่างรูปที่ครอบ" style={{width:200,height:200,borderRadius:'50%',maxWidth:'100%'}}/><label>ซูม<input type="range" min="1" max="3" step="0.01" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label>เลื่อนซ้าย–ขวา<input type="range" min="0" max="100" value={x} onChange={e=>setX(+e.target.value)}/></label><label>เลื่อนขึ้น–ลง<input type="range" min="0" max="100" value={y} onChange={e=>setY(+e.target.value)}/></label><button type="button" className="btn secondary" onClick={()=>{setPhoto(canvas.current.toDataURL('image/jpeg',0.85));setSource(null)}}>ใช้รูปนี้</button><button type="button" className="btn secondary" onClick={()=>{generation.current++;setSource(null)}}>ยกเลิกการครอบ</button></>}<p>กด “ใช้รูปนี้” แล้วกดบันทึกข้อมูล รูปจะแสดงเป็นวงกลมแทนรูป LINE</p>{error&&<p role="alert">{error}</p>}</fieldset>
}
